-- Banking System Database Schema
-- Generated by migration tool

CREATE TABLE clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rib TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    account_number INTEGER NOT NULL,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    cin TEXT NOT NULL,
    telephone TEXT NOT NULL,
    email TEXT NOT NULL,
    date_naissance TEXT NOT NULL,
    type_compte TEXT NOT NULL,
    solde REAL NOT NULL DEFAULT 0.0,
    compte_actif BOOLEAN NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    telephone TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rib TEXT NOT NULL,
    transaction_type TEXT NOT NULL,
    montant REAL,
    description TEXT,
    date_transaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (rib) REFERENCES clients (rib)
);

CREATE TABLE demands (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rib TEXT NOT NULL,
    type_demande TEXT NOT NULL,
    montant REAL,
    rib_dest TEXT,
    nouvelles_infos TEXT,
    valide BOOLEAN DEFAULT 0,
    date_demande TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (rib) REFERENCES clients (rib)
);

-- Create indexes for better performance
CREATE INDEX idx_clients_rib ON clients(rib);
CREATE INDEX idx_transactions_rib ON transactions(rib);
CREATE INDEX idx_transactions_date ON transactions(date_transaction);

